#!/usr/bin/env python

import argparse
from galaxy import get

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Get datasets from Galaxy.')
    parser.add_argument('-i', '--id', type=int, help='The dataset ID from your Galaxy history.')
    parser.add_argument('--history-id', dest="history_id", default=None, 
        help='History ID. The history ID and the dataset ID uniquly identify a dataset. Per default this is set to the current Galaxy history.')
    args = parser.parse_args()

    get( args.id, history_id )
